# Generated by Django 5.0.3 on 2024-03-08 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_post_reported_by_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='attachments',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='PostAttachment',
        ),
    ]
