# Generated by Django 4.2.2 on 2023-07-25 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_friends_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendshiprequest',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
